method: bayes
metric:
  goal: maximize
  name: rollout/ep_rew_mean
parameters:
  learning_rate:
    distribution: uniform
    max: 5e-3
    min: 1e-3
  shaped:
    values: [0, 1]

program: experiment.py